CREATE TABLE users
(
    id         VARCHAR(36) PRIMARY KEY NOT NULL,
    email      VARCHAR(255) UNIQUE     NOT NULL,
    password   VARCHAR(255)            NOT NULL,
    name       VARCHAR(100)            NOT NULL,
    nickname   VARCHAR(100) UNIQUE     NOT NULL,
    phone      VARCHAR(100) UNIQUE     NOT NULL,
    role       ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER',
    status     ENUM('ACTIVE', 'BANNED', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;